package com.iov.platform;

import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.iov.platform.common.ResourceNotFoundException;
import com.iov.platform.modules.auth.dto.LoginRequest;
import com.iov.platform.modules.vehicle.dto.VehicleCreateRequest;
import com.iov.platform.modules.vehicle.dto.VehicleUpdateRequest;
import com.iov.platform.modules.vehicle.entity.Vehicle;
import com.iov.platform.modules.vehicle.mapper.VehicleMapper;
import com.iov.platform.modules.vehicle.service.VehicleService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.messaging.simp.SimpMessagingTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import java.time.OffsetDateTime;
import java.util.Collections;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest(properties = {
    "spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1",
    "spring.datasource.driver-class-name=org.h2.Driver",
    "spring.datasource.username=sa",
    "spring.datasource.password=",
    "spring.flyway.enabled=false",
    "spring.data.redis.host=localhost",
    "spring.data.redis.port=0",
    "spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration",
    "jwt.secret=this_is_a_test_secret_key_for_jwt_at_least_32_chars_long",
    "jwt.expiration=86400000"
})
@AutoConfigureMockMvc
@ActiveProfiles("test")
@SuppressWarnings("null")
class VehicleControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private PasswordEncoder passwordEncoder;

    @MockitoBean
    private VehicleMapper vehicleMapper;

    @MockitoBean
    private VehicleService vehicleService;

    @MockitoBean
    private StringRedisTemplate stringRedisTemplate;

    @MockitoBean
    private SimpMessagingTemplate simpMessagingTemplate;

    private String adminToken;
    private String viewerToken;

    @BeforeEach
    void initTestData() throws Exception {
        jdbcTemplate.execute("DROP TABLE IF EXISTS sys_user");
        jdbcTemplate.execute("""
            CREATE TABLE sys_user (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(64) NOT NULL UNIQUE,
                password VARCHAR(128) NOT NULL,
                role VARCHAR(32) NOT NULL DEFAULT 'VIEWER',
                enabled BOOLEAN DEFAULT true,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """);

        String adminPwd = passwordEncoder.encode("admin123");
        String viewerPwd = passwordEncoder.encode("viewer123");
        jdbcTemplate.update("INSERT INTO sys_user (username, password, role, enabled) VALUES (?, ?, ?, ?)",
                "admin", adminPwd, "ADMIN", true);
        jdbcTemplate.update("INSERT INTO sys_user (username, password, role, enabled) VALUES (?, ?, ?, ?)",
                "viewer", viewerPwd, "VIEWER", true);

        adminToken = loginAndGetToken("admin", "admin123");
        viewerToken = loginAndGetToken("viewer", "viewer123");
        assertNotNull(adminToken, "Admin login failed");
        assertNotNull(viewerToken, "Viewer login failed");
    }

    private Vehicle buildVehicle(Long id, String plateNo, String model) {
        Vehicle v = new Vehicle();
        v.setId(id);
        v.setPlateNo(plateNo);
        v.setModel(model);
        v.setStatus(0);
        v.setCreatedAt(OffsetDateTime.now());
        v.setUpdatedAt(OffsetDateTime.now());
        return v;
    }

    @Test
    void createVehicle_asAdmin_success() throws Exception {
        Vehicle created = buildVehicle(1L, "沪A12345", "Tesla Model 3");
        created.setVin("LSVNV2182N2012345");
        when(vehicleService.createVehicle(any(VehicleCreateRequest.class))).thenReturn(created);

        VehicleCreateRequest req = new VehicleCreateRequest();
        req.setPlateNo("沪A12345");
        req.setVin("LSVNV2182N2012345");
        req.setModel("Tesla Model 3");

        mockMvc.perform(post("/api/vehicles")
                        .header("Authorization", "Bearer " + adminToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(req)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(0))
                .andExpect(jsonPath("$.data.plateNo").value("沪A12345"))
                .andExpect(jsonPath("$.data.vin").value("LSVNV2182N2012345"))
                .andExpect(jsonPath("$.data.model").value("Tesla Model 3"))
                .andExpect(jsonPath("$.data.status").value(0));
    }

    @Test
    void createVehicle_duplicatePlateNo_returns400() throws Exception {
        when(vehicleService.createVehicle(any(VehicleCreateRequest.class)))
                .thenThrow(new IllegalArgumentException("车牌号已存在"));

        VehicleCreateRequest req = new VehicleCreateRequest();
        req.setPlateNo("沪B67890");

        mockMvc.perform(post("/api/vehicles")
                        .header("Authorization", "Bearer " + adminToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(req)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.code").value(400))
                .andExpect(jsonPath("$.message").value("车牌号已存在"));
    }

    @Test
    void createVehicle_emptyPlateNo_returns400() throws Exception {
        VehicleCreateRequest req = new VehicleCreateRequest();
        req.setPlateNo("");

        mockMvc.perform(post("/api/vehicles")
                        .header("Authorization", "Bearer " + adminToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(req)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.code").value(400));
    }

    @Test
    void getVehicle_exists_success() throws Exception {
        Vehicle v = buildVehicle(1L, "沪C11111", "BYD Han");
        when(vehicleService.getVehicle(1L)).thenReturn(v);

        mockMvc.perform(get("/api/vehicles/1")
                        .header("Authorization", "Bearer " + adminToken))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(0))
                .andExpect(jsonPath("$.data.plateNo").value("沪C11111"));
    }

    @Test
    void getVehicle_notFound_returns404() throws Exception {
        when(vehicleService.getVehicle(99999L)).thenReturn(null);

        mockMvc.perform(get("/api/vehicles/99999")
                        .header("Authorization", "Bearer " + adminToken))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(404))
                .andExpect(jsonPath("$.message").value("车辆不存在"));
    }

    @Test
    void updateVehicle_success() throws Exception {
        Vehicle updated = buildVehicle(1L, "沪D22222", "New Model");
        when(vehicleService.updateVehicle(eq(1L), any(VehicleUpdateRequest.class))).thenReturn(updated);

        VehicleUpdateRequest req = new VehicleUpdateRequest();
        req.setPlateNo("沪D22222");
        req.setModel("New Model");

        mockMvc.perform(put("/api/vehicles/1")
                        .header("Authorization", "Bearer " + adminToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(req)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(0))
                .andExpect(jsonPath("$.data.model").value("New Model"));
    }

    @Test
    void updateVehicle_notFound_returns404() throws Exception {
        when(vehicleService.updateVehicle(eq(99999L), any(VehicleUpdateRequest.class)))
                .thenThrow(new ResourceNotFoundException("车辆不存在"));

        VehicleUpdateRequest req = new VehicleUpdateRequest();
        req.setPlateNo("沪X99999");

        mockMvc.perform(put("/api/vehicles/99999")
                        .header("Authorization", "Bearer " + adminToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(req)))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.code").value(404))
                .andExpect(jsonPath("$.message").value("车辆不存在"));
    }

    @Test
    void deleteVehicle_success() throws Exception {
        when(vehicleService.deleteVehicle(1L)).thenReturn(true);

        mockMvc.perform(delete("/api/vehicles/1")
                        .header("Authorization", "Bearer " + adminToken))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(0));
    }

    @Test
    void deleteVehicle_notFound_returns404() throws Exception {
        when(vehicleService.deleteVehicle(99999L))
                .thenThrow(new ResourceNotFoundException("车辆不存在"));

        mockMvc.perform(delete("/api/vehicles/99999")
                        .header("Authorization", "Bearer " + adminToken))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.code").value(404))
                .andExpect(jsonPath("$.message").value("车辆不存在"));
    }

    @Test
    void listVehicles_pagination_success() throws Exception {
        Page<Vehicle> page = new Page<>(1, 10);
        page.setTotal(15);
        page.setRecords(Collections.nCopies(10, buildVehicle(1L, "沪F00001", "Test")));
        when(vehicleService.listVehicles(1, 10)).thenReturn(page);

        mockMvc.perform(get("/api/vehicles")
                        .header("Authorization", "Bearer " + adminToken)
                        .param("current", "1")
                        .param("size", "10"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(0))
                .andExpect(jsonPath("$.data.records").isArray())
                .andExpect(jsonPath("$.data.total").value(15))
                .andExpect(jsonPath("$.data.size").value(10));
    }

    @Test
    void viewerCanListVehicles() throws Exception {
        Page<Vehicle> page = new Page<>(1, 10);
        page.setTotal(0);
        page.setRecords(Collections.emptyList());
        when(vehicleService.listVehicles(1, 10)).thenReturn(page);

        mockMvc.perform(get("/api/vehicles")
                        .header("Authorization", "Bearer " + viewerToken))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(0));
    }

    @Test
    void viewerCannotCreateVehicle() throws Exception {
        VehicleCreateRequest req = new VehicleCreateRequest();
        req.setPlateNo("沪G44444");

        mockMvc.perform(post("/api/vehicles")
                        .header("Authorization", "Bearer " + viewerToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(req)))
                .andExpect(status().isForbidden())
                .andExpect(jsonPath("$.code").value(403));
    }

    @Test
    void viewerCannotUpdateVehicle() throws Exception {
        VehicleUpdateRequest req = new VehicleUpdateRequest();
        req.setPlateNo("沪H55555");

        mockMvc.perform(put("/api/vehicles/1")
                        .header("Authorization", "Bearer " + viewerToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(req)))
                .andExpect(status().isForbidden())
                .andExpect(jsonPath("$.code").value(403));
    }

    @Test
    void viewerCannotDeleteVehicle() throws Exception {
        mockMvc.perform(delete("/api/vehicles/1")
                        .header("Authorization", "Bearer " + viewerToken))
                .andExpect(status().isForbidden())
                .andExpect(jsonPath("$.code").value(403));
    }

    @Test
    void unauthenticatedAccess_returns401() throws Exception {
        mockMvc.perform(get("/api/vehicles"))
                .andExpect(status().isUnauthorized())
                .andExpect(jsonPath("$.code").value(401));
    }

    private String loginAndGetToken(String username, String password) throws Exception {
        LoginRequest request = new LoginRequest();
        request.setUsername(username);
        request.setPassword(password);

        MvcResult result = mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk())
                .andReturn();

        String json = result.getResponse().getContentAsString();
        return objectMapper.readTree(json).path("data").path("token").asText(null);
    }
}
